### ISSUE TITLE
First Use Help

### ISSUE THREAD

**Issue by MarkHerhold** [musicglue/joi-ts-generator#11]
This project is a really great idea! I've run into some issues trying to use it for the first time though.

1. It seems that the project needs to have `joi` as a dependency, not a dev dependency. Installing the module globally seems to exclude `joi`.
1. It seems that `ts-node` is required to be installed globally. I will submit a PR to add a note to the README about this if you like.
1. The example in the README doesn't work for me. Some additional options are now required (`nullableMode`, `library`) (what are these BTW?) and the example only outputs a definition file with some comments. 

Any help/guidance is much appreciated! Thanks!

**Comment by alonp99** [comment]
@MarkHerhold Did you find a solution for 3?

I get:
`
   const error = new Error(message);
                  ^
ValidationError: child "joiTsGenerator" fails because [child "nullableMode" fails because ["nullableMode" is required]]
`

**Comment by MarkHerhold** [comment]
I have not. I checked the code and found it pretty confusing as well so I wasn't able to answer my own questions. The actual goal of the module/its APIs are not clear to me because it seems to be more than just TS generation.

I'm guessing you are trying to do the same thing as me. I'm currently evaluating [joi-to-swagger](https://github.com/Twipped/joi-to-swagger) to see if I can generate OpenAPI docs with my Joi schema and in turn use [`autorest`](https://github.com/Azure/autorest) to generate TS and other classes for client libraries. I have no idea if it will actually work though. 😄

**Comment by nikcorg** [comment]
In your own interest, you might want to consider another library, unless it's adopted by someone else, as it's [no longer used or maintained by the original author](https://github.com/musicglue/joi-ts-generator/pull/15#issuecomment-342548277).

For your questions, you probably want to set [`nullableMode` to be `option`](https://github.com/musicglue/joi-ts-generator/blob/cc99a88b2e05fa7687164bd7dd1ea64c0ab8e378/src/config.ts#L37) in your config. `library` is an output path you need to supply.

Sample config block in your `package.json`:

```
  "joiTsGenerator": {
    "input": "./src/generatorInputs.ts",
    "nullableMode": "option",
    "outputs": {
      "library": "./src/coercion.generated.ts",
      "optics": "./src/optics",
      "types": "./src/types.generated.ts",
      "utils": "./src/utils.generated.ts"
    }
  }
```

**Comment by MarkHerhold** [comment]
@nikcorg Could you put a warning in the README so future users know the project isn't being maintained?

**Comment by nikcorg** [comment]
Done.
